language: node_js
node_js:
- "10.12"

cache:
  directories:
  - node_modules

install: npm i

stages:
- name: test
- name: lint

jobs:
  include:
  - stage: test
    script: npm run test

  - stage: lint
    script: npm run lint